# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170602_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryApartmentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apartment')),
            ],
        ),
    ]
