# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField(max_length=300)),
                ('price', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=500)),
            ],
        ),
    ]
