# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='site',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='street',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
