# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160729_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
