# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apartment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='street',
        ),
    ]
