# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160802_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='apartment',
            name='living_space',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_m2',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
