# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160803_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='living_space',
            field=models.FloatField(blank=True),
        ),
    ]
