# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160803_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
