# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160803_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
